- name: Create docker directory
  file:
    path: /opt/docker
    state: directory
    mode: 0755

- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: /opt/docker/docker-compose.yml

- name: Start containers
  command: docker-compose up -d
  args:
    chdir: /opt/docker
