- name: Install sudo
  apt:
    name: sudo
    state: present

- name: Создать пользователей
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    groups: sudo
    append: yes
  loop: "{{ users }}"

- name: Добавить SSH ключ для пользователей
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
  loop: "{{ users }}"
